config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  root 'articles#index'
  resources :articles, :comments
  resources :users, only: [:index]
  get 'contact_us' => 'home#contact_us'
  get 'about_us' => 'home#about_us'

end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if user.role? :admin
      can :manage, :all
    elsif user.role? :moderator
      can :read, :all
      can :create, Article
      can :update, Article do |record|
        record.try(:user) == user
      end
      can :destroy, Article do |record|
        record.try(:user) == user
      end
      can :create, Comment
      can :update, Comment do |record|
        record.try(:user) == user
      end
      can :destroy, Comment do |record|
        record.try(:user) == user
      end
    else
      can :read, :all
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments, :dependent => :destroy
  belongs_to :user

  validates_presence_of :name, :content

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article
  belongs_to :user

  validates_presence_of :content

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments

  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }

  ROLES = %w[admin moderator]

  validates :name, presence: true

  before_save :capitalize_name

  def capitalize_name
    self.name = self.name.titleize
  end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end

  def role?(role)
    roles.include? role.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, notice: 'Access denied.'
  end

  # temp fix for cancan forbidden attributes error
  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < BaseController

  load_and_authorize_resource

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
    @articles = Kaminari.paginate_array(@articles).page(params[:page]).per(5)
  end

  def show
    @comment = Comment.new(:article => @article)
  end

  def new
    @article = Article.new(author_name: current_user.name)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to articles_url, notice: 'Article was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name, :content, :author_name)
    end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_filter :check_authentication

  def check_authentication
    #    unless current_user.present?
    #      redirect_to "/422.html"
    #    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < BaseController

  load_and_authorize_resource

  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
  end

  def edit
    render :json => {:success => true, :partial => render_to_string(:partial => 'comments/form', :locals => { comment: @comment })}
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      render :json => {:success => true, :partial => render_to_string(:partial => 'comments/comments', :locals => { article: @comment.article })}
    else
      render :json => {:error_fields => @comment.errors, :error_message => @comment.errors.full_messages}, :status => 500
    end
  end

  def update
    if @comment.update(comment_params)
      render :json => {:success => true, :partial => render_to_string(:partial => 'comments/comment', :locals => { comment: @comment })}
    else
      render :json => {:error_fields => @comment.errors, :error_message => @comment.errors.full_messages}, :status => 500
    end
  end

  def destroy
    if @comment.destroy
      render :json => {:success => true, :partial => render_to_string(:partial => 'comments/comments', :locals => { article: @comment.article })}
    else
      render :json => {:error_fields => @comment.errors, :error_message => @comment.errors.full_messages}, :status => 500
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:article_id, :content)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def about_us
  end

  def contact_us
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters
  before_filter :check_permissions, :only => [:new, :create]

  skip_before_filter :require_no_authentication
 
  def check_permissions
    authorize! :create, resource
  end

  def create
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :roles => [])
    devise_parameter_sanitizer.for(:account_update).push(:name, :roles => [])
  end

  def sign_up(resource_name, resource)
    true
  end

  def after_sign_up_path_for(resource)
    '/'
  end

end

app/controllers/users_controller.rb
class UsersController < BaseController

  def index
    @users = User.order(:name)
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(15)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end

end

app/views/articles/_form.html.haml
.panel.panel-default
  .panel-heading
    .panel-title
      .row
        .col-md-4
          New Article
        .col-md-8
          .pull-right
            = link_to 'Back', articles_path, class: "btn btn-info active"
  .panel-body
    = form_for(@article, :html => { :role => "form" }) do |f|
      - if @article.errors.any?
        #error_explanation
          %h2
            = pluralize(@article.errors.count, "error")
            prohibited this article from being saved:
          %ul
            - @article.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.label :name
        = f.text_field :name, :class => "form-control", :placeholder => "Enter name"
      .form-group
        = f.label :content
        = f.text_area :content, :rows => "15", :class => "form-control", :placeholder => "Enter content"
      .form-group
        = f.label :author_name
        = f.text_field :author_name, :class => "form-control", :placeholder => "Enter author name"
      .actions
        = f.submit "Submit", :class => "btn btn-danger"

app/views/articles/edit.html.haml
= render "form"

app/views/articles/index.html.haml
.panel.panel-default
  .panel-heading
    .row
      .pull-left.col-md-2
        Article
      .col-md-2
        Comments
      .col-md-2
        Author
      .col-md-2
        Created At
      .col-md-2
        Actions
      .col-md-2
        .pull-right
          - if can? :create, Article
            = link_to 'New Article', new_article_path, class: "btn btn-info active", role: "button"
  .panel-body
    - @articles.each do |article|
      %div.row.well-sm
        %div.col-md-2
          = link_to article.name, article_path(article)
        %div.col-md-2
          = article.comments.size
        %div.col-md-2
          = article.author_name
        %div.col-md-2
          = article.created_at.strftime('%b %d, %Y')
        %div.col-md-2
          - if can? :destroy, article
            %b
              %a{"data-confirm" => "Are you sure?", "data-method" => "delete", href: "/articles/#{article.id}", "class" => "btn btn-danger active"} Destroy
          - if can? :update, article
            %b= link_to 'Edit', edit_article_path(article), class: "btn btn-info active"
        %div.col-md-2

= paginate @articles, :theme => 'twitter-bootstrap-3'

app/views/articles/new.html.haml
= render "form"

app/views/articles/show.html.haml
.testing
.panel.panel-info
  .panel-heading
    .row
      .pull-left.col-md-8
        Article By
        %em
          = @article.author_name
      .col-md-4
        .pull-right
          %p
            - if can? :update, @article
              = link_to "Edit", edit_article_path(@article), class: "btn btn-info active"
            - if can? :destroy, @article
              %a{"data-confirm" => "Are you sure?", "data-method" => "delete", href: "/articles/#{@article.id}", "class" => "btn btn-danger active"} Destroy
            = link_to "Back", articles_path, class: "btn btn-info active"

  .panel-body
    %div.row.well-sm
      %div.col-md-12
        = simple_format @article.content

#comments 
  = render 'comments/comments', {article: @article}

- if can? :create, Comment
  = render :partial => 'comments/form', :locals => { comment: @comment} 

app/views/comments/_comment.html.haml
.panel-heading
  .row
    .pull-left.col-md-8
      %b= comment.user.name
      @ #{comment.updated_at.strftime('%b %d, %Y %H:%M:%S')}
      .destroy_errors.alert.alert-info.fade.in.hide
    .col-md-4
      .pull-right
        %p
          - if can? :update, comment
            = link_to "Edit", edit_comment_path(comment), class: "btn btn-info edit_comment_data"
          - if can? :destroy, comment
            = link_to "Destroy", "/comments/#{comment.id}", class: "btn btn-danger destroy_comment"
.panel-body
  .row.well-sm
    .col-md-12.comments_data
      = simple_format comment.content

app/views/comments/_comments.html.haml
- unless article.comments.empty?
  %h3= pluralize(article.comments.size, 'comment')
  .panel.panel-default
    - for comment in article.comments
      = render "comments/comment", { comment: comment }

app/views/comments/_form.html.haml
= form_for(comment, :html => { :role => "form" }) do |f|
  .error_explanation.alert.alert-info.fade.in.hide
    %button{ "class" => "close close_errors"}
      ×
    .error_details
  .form-group
    = f.label :content
    = f.text_area :content, :rows => '10', :class => "form-control", :placeholder => "Add your comment"
    = f.hidden_field :article_id
  .actions
    = f.submit "Submit", :class => "btn btn-danger"

app/views/comments/edit.html.haml
= render 'form', {comment: @comment}

app/views/comments/new.html.haml
= render 'form', {comment: @comment}

app/views/home/about_us.html.haml
%h1
  About us

app/views/home/contact_us.html.haml
%h3
  Contact Us

Email: ganni.phaneendra@gmail.com
%br
Mobile: +91 8179725354

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/_footer.html.haml
%ul.nav.nav-pills
  %li
    %a{href: "/about_us"} About us
  %li
    %a{href: "/contact_us"} Contact us

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: "/"} &nbsp Debate
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      - if current_user
        %li.active
          %a{href: "/"} Home
        %li
          %a{href: "/users"} Users
    %ul.nav.navbar-nav.navbar-right
      - if !current_user
        %li
          %a{href: "/users/sign_in"} Sign-in
      - else
        %li
          %a{href: ""}= current_user.email
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            Account Settings
            %b.caret
          %ul.dropdown-menu
            %li
              %a{href: "/users/edit"} Edit Account
            - if can? :create, User
              %li
                = link_to "Create User", new_user_registration_path
            %li.divider
            %li
              = link_to :logout, destroy_user_session_path, :method => :delete
  / /.navbar-collapse

app/views/layouts/_sidebar.html.haml
%ul.nav.nav-stacked{style: "max-width: 300px;"}
  %li
    %a{href: "/"} sidebar

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Debate
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .row
      = render :partial => "layouts/header"
    .row
      .col-md-10
        = render :partial => "layouts/flash_messages"
        - if current_user.blank?
          %h2.login_notice 
            Please signin for posting your comments
        = yield
      .col-md-2
        = render :partial => "layouts/sidebar"
    .row
      = render :partial => "layouts/footer"

app/views/users/index.html.haml
.panel.panel-default
  .panel-heading
    .row
      .pull-left.col-md-8
        User
      .col-md-2
        Roles
      .col-md-2
        .pull-right
          - if can? :create, User
            = link_to 'New User', new_user_registration_path, class: "btn btn-info active", role: "button"

  .panel-body
    - @users.each do |user|
      .row.well-sm
        .col-md-8
          = user.name
        .col-md-2
          = user.roles.join(", ")
        .col-md-2

= paginate @users, :theme => 'twitter-bootstrap-3'